apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  name: fabric2
spec:
  kind: loopback
  networkInstance: vpc-mgmt2
  prefixLength: 24
  addressFamily: ipv4
  labels:
    nephio.org/purpose: mgmt
    nephio.org/fabric: fabric2
  
